#! /usr/bin/env bash
exec /home/felipe-zorro/miniconda3/envs/digital/bin/vvp -f "$0" "$@" <<'# EOF'
:ivl_version "13.0 (devel)" "(0_8-6859-gf50cc35d2-dirty)";
:ivl_delay_selection "TYPICAL";
:vpi_time_precision + 0;
:vpi_module "/home/felipe-zorro/miniconda3/envs/digital/lib/ivl/system.vpi";
:vpi_module "/home/felipe-zorro/miniconda3/envs/digital/lib/ivl/vhdl_sys.vpi";
:vpi_module "/home/felipe-zorro/miniconda3/envs/digital/lib/ivl/vhdl_textio.vpi";
:vpi_module "/home/felipe-zorro/miniconda3/envs/digital/lib/ivl/v2005_math.vpi";
:vpi_module "/home/felipe-zorro/miniconda3/envs/digital/lib/ivl/va_math.vpi";
:vpi_module "/home/felipe-zorro/miniconda3/envs/digital/lib/ivl/v2009.vpi";
S_0x3603a520 .scope package, "$unit" "$unit" 2 1;
 .timescale 0 0;
S_0x3603a6b0 .scope module, "sqrt_datapath" "sqrt_datapath" 3 1;
 .timescale 0 0;
    .port_info 0 /INPUT 1 "clk";
    .port_info 1 /INPUT 1 "rst";
    .port_info 2 /INPUT 1 "load_data";
    .port_info 3 /INPUT 1 "shift_r_d";
    .port_info 4 /INPUT 1 "check_sub";
    .port_info 5 /INPUT 1 "dec_count";
    .port_info 6 /INPUT 16 "D_in";
    .port_info 7 /OUTPUT 8 "Q_out";
    .port_info 8 /OUTPUT 1 "count_is_0";
P_0x36047d00 .param/l "WIDTH" 0 3 2, +C4<00000000000000000000000000010000>;
L_0x360643f0 .functor BUFZ 8, v0x360632c0_0, C4<00000000>, C4<00000000>, C4<00000000>;
o0x775f0eacb018 .functor BUFZ 16, C4<zzzzzzzzzzzzzzzz>; HiZ drive
v0x3603a8e0_0 .net "D_in", 15 0, o0x775f0eacb018;  0 drivers
v0x36063120_0 .net "Q_out", 7 0, L_0x360643f0;  1 drivers
v0x36063200_0 .var "REG_D", 15 0;
v0x360632c0_0 .var "REG_Q", 7 0;
v0x360633a0_0 .var "REG_R", 9 0;
L_0x775f0ea82018 .functor BUFT 1, C4<01>, C4<0>, C4<0>, C4<0>;
v0x360634d0_0 .net/2u *"_ivl_0", 1 0, L_0x775f0ea82018;  1 drivers
L_0x775f0ea82060 .functor BUFT 1, C4<000000000000000000000000000>, C4<0>, C4<0>, C4<0>;
v0x360635b0_0 .net *"_ivl_11", 26 0, L_0x775f0ea82060;  1 drivers
L_0x775f0ea820a8 .functor BUFT 1, C4<00000000000000000000000000000000>, C4<0>, C4<0>, C4<0>;
v0x36063690_0 .net/2u *"_ivl_12", 31 0, L_0x775f0ea820a8;  1 drivers
v0x36063770_0 .net *"_ivl_8", 31 0, L_0x360644b0;  1 drivers
o0x775f0eacb1c8 .functor BUFZ 1, C4<z>; HiZ drive
v0x36063850_0 .net "check_sub", 0 0, o0x775f0eacb1c8;  0 drivers
o0x775f0eacb1f8 .functor BUFZ 1, C4<z>; HiZ drive
v0x36063910_0 .net "clk", 0 0, o0x775f0eacb1f8;  0 drivers
v0x360639d0_0 .var "count", 4 0;
v0x36063ab0_0 .net "count_is_0", 0 0, L_0x36074670;  1 drivers
o0x775f0eacb288 .functor BUFZ 1, C4<z>; HiZ drive
v0x36063b70_0 .net "dec_count", 0 0, o0x775f0eacb288;  0 drivers
o0x775f0eacb2b8 .functor BUFZ 1, C4<z>; HiZ drive
v0x36063c30_0 .net "load_data", 0 0, o0x775f0eacb2b8;  0 drivers
v0x36063cf0_0 .net "r_ge_test", 0 0, L_0x36064300;  1 drivers
o0x775f0eacb318 .functor BUFZ 1, C4<z>; HiZ drive
v0x36063db0_0 .net "rst", 0 0, o0x775f0eacb318;  0 drivers
o0x775f0eacb348 .functor BUFZ 1, C4<z>; HiZ drive
v0x36063f80_0 .net "shift_r_d", 0 0, o0x775f0eacb348;  0 drivers
v0x36064040_0 .net "test_val", 9 0, L_0x36064240;  1 drivers
E_0x360475c0 .event posedge, v0x36063db0_0, v0x36063910_0;
L_0x36064240 .concat [ 2 8 0 0], L_0x775f0ea82018, v0x360632c0_0;
L_0x36064300 .cmp/ge 10, v0x360633a0_0, L_0x36064240;
L_0x360644b0 .concat [ 5 27 0 0], v0x360639d0_0, L_0x775f0ea82060;
L_0x36074670 .cmp/eq 32, L_0x360644b0, L_0x775f0ea820a8;
    .scope S_0x3603a6b0;
T_0 ;
    %wait E_0x360475c0;
    %load/vec4 v0x36063db0_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_0.0, 8;
    %pushi/vec4 0, 0, 16;
    %assign/vec4 v0x36063200_0, 0;
    %pushi/vec4 0, 0, 10;
    %assign/vec4 v0x360633a0_0, 0;
    %pushi/vec4 0, 0, 8;
    %assign/vec4 v0x360632c0_0, 0;
    %pushi/vec4 0, 0, 5;
    %assign/vec4 v0x360639d0_0, 0;
    %jmp T_0.1;
T_0.0 ;
    %load/vec4 v0x36063c30_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_0.2, 8;
    %load/vec4 v0x3603a8e0_0;
    %assign/vec4 v0x36063200_0, 0;
    %pushi/vec4 0, 0, 10;
    %assign/vec4 v0x360633a0_0, 0;
    %pushi/vec4 0, 0, 8;
    %assign/vec4 v0x360632c0_0, 0;
    %pushi/vec4 8, 0, 5;
    %assign/vec4 v0x360639d0_0, 0;
T_0.2 ;
    %load/vec4 v0x36063f80_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_0.4, 8;
    %load/vec4 v0x360633a0_0;
    %parti/s 8, 0, 2;
    %load/vec4 v0x36063200_0;
    %parti/s 2, 14, 5;
    %concat/vec4; draw_concat_vec4
    %assign/vec4 v0x360633a0_0, 0;
    %load/vec4 v0x36063200_0;
    %parti/s 14, 0, 2;
    %concati/vec4 0, 0, 2;
    %assign/vec4 v0x36063200_0, 0;
T_0.4 ;
    %load/vec4 v0x36063850_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_0.6, 8;
    %load/vec4 v0x36063cf0_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_0.8, 8;
    %load/vec4 v0x360633a0_0;
    %load/vec4 v0x36064040_0;
    %sub;
    %assign/vec4 v0x360633a0_0, 0;
    %load/vec4 v0x360632c0_0;
    %parti/s 7, 0, 2;
    %concati/vec4 1, 0, 1;
    %assign/vec4 v0x360632c0_0, 0;
    %jmp T_0.9;
T_0.8 ;
    %load/vec4 v0x360632c0_0;
    %parti/s 7, 0, 2;
    %concati/vec4 0, 0, 1;
    %assign/vec4 v0x360632c0_0, 0;
T_0.9 ;
T_0.6 ;
    %load/vec4 v0x36063b70_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_0.10, 8;
    %load/vec4 v0x360639d0_0;
    %subi 1, 0, 5;
    %assign/vec4 v0x360639d0_0, 0;
T_0.10 ;
T_0.1 ;
    %jmp T_0;
    .thread T_0;
# The file index is used to find the file name in the following table.
:file_names 4;
    "N/A";
    "<interactive>";
    "-";
    "sqrt_datapath.v";
# EOF
